In [1]:
import googletrans
from googletrans import Translator
import pandas as pd
from tqdm import tqdm

In [2]:
from googletrans import Translator
translator = Translator(service_urls=[
      'translate.google.com',
      'translate.google.co.uk',
      'translate.google.nl'
    ])

In [3]:
df = pd.read_csv('dataentries.csv')

C:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,id,image_id,origin_id,caption,Translated,type,is_translated,created_at,updated_at
0,0,0,0,0,500,318556,48,A very clean and well decorated empty bathroom,حمام خالی بسیار تمیز و به خوبی تزئین شده,1,1,1/10/2020 0:00,1/10/2020 0:00
1,1,1,1,1,501,116100,67,A panoramic view of a kitchen and all of its a...,یک نمای پانوراما از یک آشپزخانه و لوازم آن است.,1,1,1/10/2020 0:00,1/10/2020 0:00
2,2,2,2,2,502,318556,126,A blue and white bathroom with butterfly theme...,حمام آبی و سفید با پروانه کاشی دیوار مضمون.,1,1,1/10/2020 0:00,1/10/2020 0:00
3,3,3,3,3,503,116100,148,A panoramic photo of a kitchen and dining room,یک عکس پانورامایی از یک اتاق آشپزخانه و ناهار ...,1,1,1/10/2020 0:00,1/10/2020 0:00
4,4,4,4,4,504,379340,173,A graffiti-ed stop sign across the street from...,علامت توقف گرافیتی اد سراسر خیابان را از یک ما...,1,1,1/10/2020 0:00,1/10/2020 0:00

In [5]:
if "Translated" in df.columns:
    pass
else:
    df.insert(4, "Translated", None)

In [6]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,id,image_id,origin_id,caption,Translated,type,is_translated,created_at,updated_at
0,0,0,0,0,500,318556,48,A very clean and well decorated empty bathroom,حمام خالی بسیار تمیز و به خوبی تزئین شده,1,1,1/10/2020 0:00,1/10/2020 0:00
1,1,1,1,1,501,116100,67,A panoramic view of a kitchen and all of its a...,یک نمای پانوراما از یک آشپزخانه و لوازم آن است.,1,1,1/10/2020 0:00,1/10/2020 0:00
2,2,2,2,2,502,318556,126,A blue and white bathroom with butterfly theme...,حمام آبی و سفید با پروانه کاشی دیوار مضمون.,1,1,1/10/2020 0:00,1/10/2020 0:00
3,3,3,3,3,503,116100,148,A panoramic photo of a kitchen and dining room,یک عکس پانورامایی از یک اتاق آشپزخانه و ناهار ...,1,1,1/10/2020 0:00,1/10/2020 0:00
4,4,4,4,4,504,379340,173,A graffiti-ed stop sign across the street from...,علامت توقف گرافیتی اد سراسر خیابان را از یک ما...,1,1,1/10/2020 0:00,1/10/2020 0:00

In [7]:
result = list()
for i, item in tqdm(enumerate(df['caption'])):

    if df.at[i,'is_translated'] == 0:
        try:
            translations = translator.translate([item], dest='fa')
            for translation in translations:
                    try:
                        df.at[i,'is_translated'] = 1 
                        df.at[i,'Translated'] = translation.text
                    except:
                        pass
        except:
            print("There is not enough volume.")
            break
            
print('Done!')

86473it [9:13:46,  2.60it/s]

There is not enough volume.
Done!

In [8]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,id,image_id,origin_id,caption,Translated,type,is_translated,created_at,updated_at
0,0,0,0,0,500,318556,48,A very clean and well decorated empty bathroom,حمام خالی بسیار تمیز و به خوبی تزئین شده,1,1,1/10/2020 0:00,1/10/2020 0:00
1,1,1,1,1,501,116100,67,A panoramic view of a kitchen and all of its a...,یک نمای پانوراما از یک آشپزخانه و لوازم آن است.,1,1,1/10/2020 0:00,1/10/2020 0:00
2,2,2,2,2,502,318556,126,A blue and white bathroom with butterfly theme...,حمام آبی و سفید با پروانه کاشی دیوار مضمون.,1,1,1/10/2020 0:00,1/10/2020 0:00
3,3,3,3,3,503,116100,148,A panoramic photo of a kitchen and dining room,یک عکس پانورامایی از یک اتاق آشپزخانه و ناهار ...,1,1,1/10/2020 0:00,1/10/2020 0:00
4,4,4,4,4,504,379340,173,A graffiti-ed stop sign across the street from...,علامت توقف گرافیتی اد سراسر خیابان را از یک ما...,1,1,1/10/2020 0:00,1/10/2020 0:00

In [9]:
df.to_csv(r'out_of_res\result.csv',encoding='utf-8-sig')

In [10]:
df.to_csv('dataentries.csv',encoding='utf-8-sig')